version: '3.7'

services:
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - 8000:8000
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    restart: always
    ports:
      - 7999:8001
    environment:
      DYNAMO_ENDPOINT: http://host.docker.internal:8000
      AWS_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    depends_on:
      - dynamodb
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: products-scrape-job-topic:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper